Repository jvondermarck/dinosaur-exploder, pull requests merged in 2025-04, with the labels that each got.

#151 #150 Implemented a settings system. Currently only for the sound volume.
  .gitignore
  src/main/java/com/dinosaur/dinosaurexploder/controller/DinosaurController.java
  src/main/java/com/dinosaur/dinosaurexploder/controller/SettingsController.java
  src/main/java/com/dinosaur/dinosaurexploder/model/GreenDinoComponent.java
  src/main/java/com/dinosaur/dinosaurexploder/model/Player.java
  src/main/java/com/dinosaur/dinosaurexploder/model/PlayerComponent.java
  src/main/java/com/dinosaur/dinosaurexploder/model/Settings.java
  src/main/java/com/dinosaur/dinosaurexploder/view/DinosaurMenu.java
  src/main/java/com/dinosaur/dinosaurexploder/view/ShipSelectionMenu.java
Labels: help wanted

#167 [Feature] selected language is now also stored in the settings file.
  src/main/java/com/dinosaur/dinosaurexploder/model/Settings.java
  src/main/java/com/dinosaur/dinosaurexploder/utils/SettingsProvider.java
  src/main/java/com/dinosaur/dinosaurexploder/view/DinosaurMenu.java
Labels: status: in-review

#175 [Fix] Different game versions being displayed
  src/main/java/com/dinosaur/dinosaurexploder/model/GameConstants.java
  src/main/java/com/dinosaur/dinosaurexploder/view/DinosaurGUI.java
  src/main/java/com/dinosaur/dinosaurexploder/view/PauseMenu.java
Labels: status: in-review

#186 [Feature]: Dinos can drop ❤️ once killed
  src/main/java/com/dinosaur/dinosaurexploder/components/Heart.java
  src/main/java/com/dinosaur/dinosaurexploder/components/Life.java
  src/main/java/com/dinosaur/dinosaurexploder/components/LifeComponent.java
  src/main/java/com/dinosaur/dinosaurexploder/constants/EntityType.java
  src/main/java/com/dinosaur/dinosaurexploder/constants/GameConstants.java
  src/main/java/com/dinosaur/dinosaurexploder/controller/DinosaurController.java
  src/main/java/com/dinosaur/dinosaurexploder/model/GameEntityFactory.java
  src/main/resources/assets/sounds/heartHit.wav
Labels: status: pending-conflict-resolution
